### ISSUE TITLE
output not working

### ISSUE THREAD

**Issue by tlc** [kung-foo/multiregion-terraform#1]
$ terraform apply
...
module.cdn-us-east-1.aws_instance.server.2: Refreshing state... (ID: i-07aff46adf10f484b)
module.cdn-us-east-1.aws_instance.server.3: Refreshing state... (ID: i-0d0f94dad51525ecf)
module.cdn-us-east-1.aws_instance.server.1: Refreshing state... (ID: i-0cfc5fceaf74149c5)
module.cdn-us-east-1.aws_instance.server.0: Refreshing state... (ID: i-0c2d0931931733db4)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
$ terraform output
The state file has no outputs defined. Define an output
in your configuration with the `output` directive and re-run
`terraform apply` for it to become available.

**Comment by tlc** [comment]
Sorry!  Just saw the mention in the README!

**Comment by kung-foo** [comment]
No problem. I need to update the docs to show other ways to list the EIPs.

**Comment by kung-foo** [comment]
@tlc you can use [jq](https://stedolan.github.io/jq/) to dump all the servers from the tfstate:

```
$ jq '[.modules[] | select(.outputs.servers.value != null) | .outputs.servers.value[] ]' terraform.tfstate
[
  "52.199.99.175",
  "52.193.39.37",
  "52.78.183.148",
  "52.78.230.74",
  "35.154.67.193",
  "35.154.47.136",
  "52.77.254.174",
  "52.221.244.90",
  "13.54.91.109",
  "13.54.35.0",
...
]
```

**Comment by tlc** [comment]
Thanks.  I also found out I could reference the module outputs as follows.

```
output "servers" {
    value = [
                "${module.cdn-us-east-1.servers}",
                "${module.cdn-us-east-2.servers}",
...]}
```

(I'm new to Terraform.)  But my real goal was creating an ansible inventory which proved too difficult within Terraform.  So I'm now evaluating dynamic inventory generators that read .tfstate.
